### PR TITLE
Add `unresolvable` property to `ModuleTypeDefinition`

### PR DESCRIPTION
**Pull request by robbiepitts**
Goes along with https://github.com/glimmerjs/resolution-map-builder/pull/26

### CODE REVIEW

**Comment by rwjblue** [comment]
released as 0.3.1

**Comment by mixonic** [comment]
Why is the collection being unresolvable not sufficient?

**Comment by robbiepitts** [comment]
@mixonic Given a file tree like this...

```
src
└── ui
    └── components
        └── hello-glimmer
            ├── component-test.ts
            ├── component.ts
            └── template.hbs
```

... we want to be able to ignore `component-test.ts`.

**Comment by mixonic** [comment]
oof. Ok, I see in the other PR's diff now.

**Pull request merged**
